GET http://3.234.211.38:5000

###
POST   http://3.234.211.38:5000
Content-Type: application/json

{
    "title":"not working third post",
    "content":"third content",
    "tag":"posts",
    "likes":50,
    "dislikes":30
}
###
GET     http://3.234.211.38:5000/like/1
Content-Type: application/json

{
    "id":2,
    "likes":13,
    "dislikes":4
}